layout_spectrum: 0.7984787
color:
  saturation: 0.5131578
  lightness: 0.7898338
  brandStrength: 0.6880282
  brandColors:
    - '#FFFFFF'
    - '#130F0E'
    - '#AC9A74'
    - '#FBB764'
    - '#7ED4FD'
  rhythmicContrast: 0.5320118
typography_spectrum: 0.4000678
name: Disctrict13
